-- AlterTable
ALTER TABLE "pets" ALTER COLUMN "about" DROP NOT NULL,
ALTER COLUMN "age" DROP DEFAULT,
ALTER COLUMN "images" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "adoptionRequirements" SET DEFAULT ARRAY[]::TEXT[];
